name: Sync upstream to origin
on:
  schedule:
  - cron: "0 15 * * *" # KST 00시
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/TBXark/ChatGPT-Telegram-Workers"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
